### ISSUE TITLE
你好！我好奇你开发百科使用的是什么UI库是GTK+吗

### ISSUE THREAD

**Issue by miaoxu1com** [tpxxn/JiHuangBaiKe#1]

**Comment by tpxxn** [comment]
是微软自己的WPF

**Comment by miaoxu1com** [comment]
感谢，你的反馈，又学到了 @tpxxn ，这个软件做的很好让我知道，原来软件UI还可以做的漂亮，体验也很好

**Comment by tpxxn** [comment]
@miaoxu1com 也是最近刚学的= =

**Comment by miaoxu1com** [comment]
已经 很不错 @tpxxn 看你你做的软件我也有想学的意思了 我是学php

**Comment by tpxxn** [comment]
@miaoxu1com  (*^__^*)  喜欢就来学吧~
